// import './singleton.js'
// import './strategy.js'
// import './proxy.js'
// import './iterator.js'
// import './publish-sub.js'
// import './command.js'
// import './composite.js'
import './template-method.js'